# Welcome to Jekyll!
# Site settings
title: Venture
email: zacharymoring@gmail.com
description:
  Documents and homebrew for _Venture_, an Exalted 3rd Edition Dragon-Blooded
  game.
baseurl: "/venture" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ElectronSutra

# Template settings
heading_anchors: true
color_scheme: dark

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
